# cache_config:
#   end_point: /cache_end_point
# job_deployment_env: local_docker_scheduler_plugin
job_results_root: ${FOUNDATIONS_HOME}/job_data
container_config_root: ${FOUNDATIONS_HOME}/config/local_docker_scheduler/worker_config
scheduler_url: http://127.0.0.1:5558
working_dir_root: ${FOUNDATIONS_HOME}/local_docker_scheduler/work_dir
