cache_config:
  end_point: /cache_end_point
container_config_root: ${REMOTE_FOUNDATIONS_HOME}/config/local_docker_scheduler/worker_config
job_deployment_env: local_docker_scheduler_plugin
job_results_root: ${REMOTE_FOUNDATIONS_HOME}/job_data
scheduler_url: http://${LOCAL_DOCKER_SCHEDULER_HOST}:5558
working_dir_root: ${REMOTE_FOUNDATIONS_HOME}/local_docker_scheduler/work_dir
